# Generated by Django 4.2.3 on 2023-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_portfolio_service_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.CharField(blank=True, max_length=200, null=True)),
                ('premium', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
